name: check-pr

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: swift build

      - name: Test
        run: swift test
        
      - name: Lint with cocoapods
        run: pod lib lint --allow-warnings